"""Проверка памяти Supabase: подключение, создание таблицы, запись, чтение.

Запуск:  python supa_probe.py
"""
import os

from supabase import create_client

url = os.getenv("SUPABASE_URL", "")
key = os.getenv("SUPABASE_KEY", "")

lines = [f"url set: {bool(url)}", f"key set: {bool(key)} len={len(key)}"]

if not url or not key:
    lines.append("RESULT: no credentials in environment")
else:
    c = create_client(url, key)
    lines.append(f"client ok, url={url[:40]}...")

    # 1. Проверяем доступ к таблице
    try:
        rows = c.table("agent_messages").select("*").limit(1).execute()
        lines.append(f"SELECT ok, rows={len(rows.data)}")
        table_exists = True
    except Exception as e:
        lines.append(f"SELECT failed: {type(e).__name__} {str(e)[:200]}")
        table_exists = False

    # 2. Пробуем создать таблицу обычным путём (через SQL RPC, если есть)
    ddl = """
    create table if not exists agent_messages (
        id bigint generated by default as identity primary key,
        session_id text not null,
        role text not null,
        content text not null,
        created_at timestamptz default now()
    );
    create index if not exists agent_messages_session_idx
        on agent_messages(session_id, id);
    """
    try:
        c.rpc("exec", {"sql": ddl}).execute()
        lines.append("RPC exec: OK")
    except Exception as e:
        lines.append(f"RPC exec failed: {type(e).__name__} {str(e)[:200]}")
        lines.append("  -> need to create table via Supabase SQL editor")

    # 3. Пробуем записать, если таблица есть
    if table_exists:
        try:
            c.table("agent_messages").insert({
                "session_id": "probe", "role": "user", "content": "проверка связи",
            }).execute()
            lines.append("INSERT ok")
            got = c.table("agent_messages").select("*").eq(
                "session_id", "probe").execute()
            lines.append(f"SELECT back rows={len(got.data)}")
            if got.data:
                lines.append(f"content read back: {got.data[0]['content']!r}")
            c.table("agent_messages").delete().eq("session_id", "probe").execute()
            lines.append("cleanup ok")
        except Exception as e:
            lines.append(f"INSERT failed: {type(e).__name__} {str(e)[:200]}")

with open("reports/supa_probe.txt", "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print("written reports/supa_probe.txt")