"""Проекты, память о пользователе и журнал действий.

Три сущности, которые делают агента полноценным сервисом, а не
одноразовым чатом:

1. Проекты — у каждого своя изолированная папка и своя переписка.
   Файлы лежат в Storj (S3), список проектов - в Supabase.
   Переключение проекта не требует перезапуска сервера.

2. Факты — долговременная память: кто пользователь, что за проекты,
   предпочтения. Агент читает их в начале разговора и может
   дописывать сам, когда узнаёт новое.

3. Журнал действий — каждая операция агента сохраняется, поэтому
   можно посмотреть, что он делал, даже если чат потерялся.

Всё хранится в Supabase, файлы проектов - в Storj. Схема создаётся
автоматически через Management API (см. ensure_schema).
"""
from __future__ import annotations

import hashlib
import json
import re
from datetime import datetime, timezone

from . import config, storage

_client = None
_unavailable = False

PROJECTS = "agent_projects"
FACTS = "agent_facts"
ACTIONS = "agent_actions"

DEFAULT_PROJECT = "default"

# Имя проекта превращается в безопасный префикс для папки в Storj
_SAFE = re.compile(r"[^a-zA-Z0-9_-]+")


def _get_client():
    global _client, _unavailable
    if _unavailable:
        return None
    if _client is not None:
        return _client
    if not config.memory_enabled():
        _unavailable = True
        return None
    try:
        from supabase import create_client

        _client = create_client(config.SUPABASE_URL, config.SUPABASE_KEY)
        return _client
    except Exception:
        _unavailable = True
        return None


def slug(name: str) -> str:
    """Безопасное имя папки для Storj.

    Нельзя молча сквошить разные имена в один slug: «Мой сайт» и
    «Мой-сайт» стали бы одним проектом, и проекты смешивались бы.
    Поэтому при коллизии добавляем короткий хеш от исходного имени.
    """
    raw = (name or "").strip()
    lowered = raw.lower()

    # Системный проект должен называться ровно "default", без хвоста,
    # иначе пути и проверки в коде начинают расходиться.
    if not raw or lowered == DEFAULT_PROJECT:
        return DEFAULT_PROJECT

    base = _SAFE.sub("-", lowered).strip("-")[:40]
    if not base:
        base = DEFAULT_PROJECT
    # Хвост из хеша сохраняет различимость похожих названий:
    # «Мой сайт» и «Мой-сайт» не должны слиться в один проект.
    tail = hashlib.sha1(raw.encode("utf-8")).hexdigest()[:6]
    return f"{base}-{tail}"


# ---------------------------------------------------------------------------
# Схема
# ---------------------------------------------------------------------------

DDL = f"""
create table if not exists {PROJECTS} (
    id bigint generated by default as identity primary key,
    name text not null unique,
    slug text not null unique,
    description text default '',
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

create table if not exists {FACTS} (
    id bigint generated by default as identity primary key,
    scope text not null default 'user',
    ref text not null default '',
    key text not null,
    value text not null,
    source text default '',
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);
create unique index if not exists agent_facts_uniq
    on {FACTS}(scope, ref, key);

create table if not exists {ACTIONS} (
    id bigint generated by default as identity primary key,
    project text not null default 'default',
    session_id text default '',
    kind text not null,
    tool text default '',
    detail text default '',
    ok boolean default true,
    created_at timestamptz default now()
);
create index if not exists agent_actions_proj
    on {ACTIONS}(project, id desc);
"""


def ensure_schema() -> dict:
    """Создаёт все таблицы. Работает через Management API."""
    client = _get_client()
    if client is None:
        return {"ok": False, "reason": "нет подключения к Supabase"}

    token = config.SUPABASE_ACCESS_TOKEN
    ref = config.SUPABASE_PROJECT_REF
    if token and ref:
        try:
            import httpx

            r = httpx.post(
                f"https://api.supabase.com/v1/projects/{ref}/database/query",
                headers={"Authorization": f"Bearer {token}",
                         "Content-Type": "application/json"},
                json={"query": DDL},
                timeout=60.0,
            )
            if r.status_code < 300:
                return {"ok": True, "method": "management_api"}
            detail = r.text[:200]
        except Exception as exc:
            detail = f"{type(exc).__name__}: {exc}"

        try:
            client.table(PROJECTS).select("name").limit(1).execute()
            return {"ok": True, "method": "already_exists",
                    "note": f"Management API: {detail}"}
        except Exception:
            return {"ok": False, "reason": detail}

    # Без токена только проверяем доступ
    try:
        client.table(PROJECTS).select("name").limit(1).execute()
        return {"ok": True, "method": "already_exists"}
    except Exception as exc:
        return {"ok": False, "reason": f"{type(exc).__name__}: {str(exc)[:150]}"}


# ---------------------------------------------------------------------------
# Проекты
# ---------------------------------------------------------------------------

def create_project(name: str, description: str = "") -> dict:
    """Создаёт проект и папку для его файлов.

    Повторный вызов с тем же именем обновляет описание, а не создаёт дубль.
    """
    name = (name or "").strip()
    if not name:
        return {"ok": False, "error": "Имя проекта пустое"}

    s = slug(name)
    # Физически создаём папку проекта в workspace
    p_dir = config.project_dir(s)

    client = _get_client()
    if client is None:
        # Локальный режим без Supabase
        return {
            "ok": True,
            "action": "created",
            "name": name,
            "slug": s,
            "description": description,
            "local": True,
            "path": str(p_dir),
        }

    # Ищем по имени: переименование меняет slug, а имя остаётся ключом
    existing = get_project(name)
    if existing:
        try:
            patch = {"updated_at": datetime.now(timezone.utc).isoformat()}
            if description:
                patch["description"] = description.strip()[:500]
            (client.table(PROJECTS).update(patch)
             .eq("slug", existing["slug"]).execute())
            return {"ok": True, "action": "updated", "name": name,
                    "slug": existing["slug"], "path": str(p_dir)}
        except Exception as exc:
            return {"ok": False,
                    "error": f"{type(exc).__name__}: {str(exc)[:200]}"}

    row = {
        "name": name,
        "slug": s,
        "description": (description or "").strip()[:500],
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    try:
        client.table(PROJECTS).insert(row).execute()
        return {"ok": True, "action": "created", **row, "path": str(p_dir)}
    except Exception as exc:
        return {"ok": False, "error": f"{type(exc).__name__}: {str(exc)[:200]}"}


def _count_files(s: str) -> int:
    d = config.WORKSPACE / s
    if not d.is_dir():
        return 0
    try:
        return sum(1 for p in d.rglob("*") if p.is_file() and not any(part.startswith(".") for part in p.parts))
    except Exception:
        return 0


def list_projects() -> list[dict]:
    """Все проекты, объединённые из Supabase и локальной папки workspace."""
    client = _get_client()
    seen_slugs = set()
    out = []

    if client is not None:
        try:
            r = (client.table(PROJECTS)
                 .select("name, slug, description, updated_at, created_at")
                 .order("updated_at", desc=True)
                 .execute())
            for row in (r.data or []):
                s = row.get("slug")
                if s:
                    seen_slugs.add(s)
                    out.append({
                        "name": row.get("name") or s,
                        "slug": s,
                        "description": row.get("description") or "",
                        "updated_at": str(row.get("updated_at", "")),
                        "created_at": str(row.get("created_at", "")),
                        "files": _count_files(s),
                    })
        except Exception:
            pass

    # Всегда гарантируем наличие default проекта
    if "default" not in seen_slugs:
        config.project_dir("default")
        out.insert(0, {
            "name": "default",
            "slug": "default",
            "description": "Основной проект",
            "updated_at": datetime.now(timezone.utc).isoformat(),
            "created_at": datetime.now(timezone.utc).isoformat(),
            "files": _count_files("default"),
        })
        seen_slugs.add("default")

    # Добавляем локальные папки из workspace, если их ещё нет в Supabase
    try:
        for entry in config.WORKSPACE.iterdir():
            if entry.is_dir() and not entry.name.startswith("."):
                s = entry.name
                if s not in seen_slugs:
                    seen_slugs.add(s)
                    out.append({
                        "name": s,
                        "slug": s,
                        "description": "Локальная папка проекта",
                        "updated_at": datetime.fromtimestamp(entry.stat().st_mtime, timezone.utc).isoformat(),
                        "created_at": datetime.fromtimestamp(entry.stat().st_ctime, timezone.utc).isoformat(),
                        "files": _count_files(s),
                    })
    except Exception:
        pass

    return out


def get_project(name: str) -> dict | None:
    """Один проект по имени или slug."""
    s = slug(name)
    for p in list_projects():
        if p["slug"] == s or p["name"].lower() == (name or "").lower():
            return p
    return None


def delete_project(name: str) -> dict:
    """Удаляет проект. Файлы в Storj НЕ трогаются."""
    client = _get_client()
    if client is None:
        return {"ok": False, "error": "нет подключения к Supabase"}
    s = slug(name)
    try:
        r = client.table(PROJECTS).delete().eq("slug", s).execute()
        if getattr(r, "data", None):
            return {"ok": True, "deleted": s,
                    "note": "Файлы проекта в облаке остались нетронутыми"}
        return {"ok": False, "error": f"Проект «{name}» не найден"}
    except Exception as exc:
        return {"ok": False, "error": f"{type(exc).__name__}: {str(exc)[:200]}"}


def ensure_default() -> dict:
    """Гарантирует, что есть проект default - иначе работать не с чем."""
    if get_project(DEFAULT_PROJECT):
        return get_project(DEFAULT_PROJECT)
    res = create_project(
        DEFAULT_PROJECT, "Основной проект: файлы и переписка")
    return res if res.get("ok") else {"name": DEFAULT_PROJECT,
                                       "slug": DEFAULT_PROJECT}


# ---------------------------------------------------------------------------
# Факты (память о пользователе и проектах)
# ---------------------------------------------------------------------------

def set_fact(scope: str, key: str, value: str, ref: str = "",
             source: str = "") -> dict:
    """Запоминает факт. scope: user или project. ref - имя проекта."""
    client = _get_client()
    if client is None:
        return {"ok": False, "error": "нет подключения к Supabase"}
    scope = (scope or "user").strip().lower()
    key = (key or "").strip().lower().replace(" ", "_")[:60]
    value = (value or "").strip()[:2000]
    if not key or not value:
        return {"ok": False, "error": "Нужны ключ и значение"}

    ref = slug(ref) if scope == "project" and ref else (ref or "")
    row = {"scope": scope, "ref": ref, "key": key, "value": value,
           "source": (source or "")[:100],
           "updated_at": datetime.now(timezone.utc).isoformat()}
    try:
        upd = (client.table(FACTS).update(row)
               .eq("scope", scope).eq("ref", ref).eq("key", key).execute())
        if getattr(upd, "data", None):
            return {"ok": True, "action": "updated", **row}
        client.table(FACTS).insert(row).execute()
        return {"ok": True, "action": "created", **row}
    except Exception as exc:
        return {"ok": False, "error": f"{type(exc).__name__}: {str(exc)[:200]}"}


def get_facts(scope: str = "user", ref: str = "",
              limit: int = 100) -> list[dict]:
    """Факты по области. scope: all, user или project."""
    client = _get_client()
    if client is None:
        return []
    try:
        q = client.table(FACTS).select("scope, ref, key, value, updated_at")
        if scope != "all":
            q = q.eq("scope", scope)
            if scope == "project" and ref:
                q = q.eq("ref", slug(ref))
        r = q.order("id", desc=False).limit(limit).execute()
        return [{"scope": x.get("scope"), "ref": x.get("ref", ""),
                 "key": x.get("key"), "value": x.get("value"),
                 "updated_at": str(x.get("updated_at", ""))}
                for x in (r.data or [])]
    except Exception:
        return []


def delete_fact(key: str, scope: str = "user", ref: str = "") -> dict:
    client = _get_client()
    if client is None:
        return {"ok": False, "error": "нет подключения к Supabase"}
    try:
        q = (client.table(FACTS).delete()
             .eq("scope", scope).eq("key", key.strip().lower()))
        if scope == "project" and ref:
            q = q.eq("ref", slug(ref))
        r = q.execute()
        if getattr(r, "data", None) is not None:
            return {"ok": True, "deleted": key}
        return {"ok": False, "error": f"Факт «{key}» не найден"}
    except Exception as exc:
        return {"ok": False, "error": f"{type(exc).__name__}: {str(exc)[:200]}"}


def facts_digest(project: str = "") -> str:
    """Готовая строка для системного промпта: что агент помнит."""
    parts: list[str] = []
    user = get_facts("user")
    if user:
        parts.append("О пользователе:\n" + "\n".join(
            f"- {f['key']}: {f['value']}" for f in user))
    if project:
        proj = get_facts("project", project)
        if proj:
            parts.append(f"О проекте «{project}»:\n" + "\n".join(
                f"- {f['key']}: {f['value']}" for f in proj))
    if not parts:
        return ""
    return ("Долговременная память (записана самим агентом, "
            "не выдумана):\n" + "\n\n".join(parts))


# ---------------------------------------------------------------------------
# Журнал действий
# ---------------------------------------------------------------------------

def log_action(kind: str, tool: str = "", detail: str = "",
               project: str = DEFAULT_PROJECT, session_id: str = "",
               ok: bool = True) -> bool:
    """Записывает действие агента в журнал."""
    client = _get_client()
    if client is None:
        return False
    try:
        client.table(ACTIONS).insert({
            "project": slug(project) if project else DEFAULT_PROJECT,
            "session_id": session_id[:100],
            "kind": kind[:40],
            "tool": tool[:60],
            "detail": (detail or "")[:1500],
            "ok": bool(ok),
        }).execute()
        return True
    except Exception:
        return False


def list_actions(project: str = "", limit: int = 100) -> list[dict]:
    """Журнал действий, свежие сверху."""
    client = _get_client()
    if client is None:
        return []
    try:
        q = client.table(ACTIONS).select(
            "project, session_id, kind, tool, detail, ok, created_at")
        if project:
            q = q.eq("project", slug(project))
        r = q.order("id", desc=True).limit(max(1, min(limit, 500))).execute()
        return [{
            "project": x.get("project"),
            "session_id": x.get("session_id", ""),
            "kind": x.get("kind"),
            "tool": x.get("tool", ""),
            "detail": x.get("detail", ""),
            "ok": x.get("ok", True),
            "created_at": str(x.get("created_at", "")),
        } for x in (r.data or [])]
    except Exception:
        return []


# ---------------------------------------------------------------------------
# Файлы проекта в облаке
# ---------------------------------------------------------------------------

def project_prefix(project: str) -> str:
    """Префикс папки проекта в Storj: projects/<slug>/"""
    return f"projects/{slug(project)}"


def list_project_files(project: str, limit: int = 300) -> list[dict]:
    """Файлы проекта в облаке."""
    prefix = project_prefix(project)
    keys = storage.list_keys(prefix)
    out = []
    for k in keys[:limit]:
        rel = k[len(prefix):].lstrip("/")
        if not rel:
            continue
        out.append({"key": k, "path": rel,
                    "is_dir": rel.endswith("/")})
    return out


def status() -> dict:
    """Состояние для /api/status."""
    client = _get_client()
    if client is None:
        return {"enabled": False, "projects": 0, "facts": 0}
    counts = {}
    for name, table in (("projects", PROJECTS), ("facts", FACTS),
                        ("actions", ACTIONS)):
        try:
            r = client.table(table).select("id", count="exact").execute()
            counts[name] = r.count or 0
        except Exception:
            counts[name] = 0
    return {"enabled": True, **counts}