"""Хранилище секретов: шифрованное, вне рабочей папки проекта.

Зачем это нужно
---------------
Агенту нужны ключи (Render API Token, GitHub Token), чтобы управлять
инфраструктурой. Но если положить их в .env проекта или в файл рядом
с кодом, они уедут в git при первом же пуше.

Решение: секреты лежат в Supabase, зашифрованные алгоритмом Fernet
(симметричное шифрование из библиотеки cryptography). Ключ шифрования
выводится из ADMIN_TOKEN, который уже есть на сервере Render и в
переменных окружения — то есть мастер-ключ никогда не хранится рядом
с данными и не попадает в репозиторий.

Что это НЕ делает
-----------------
Это не защита от владельца сервера — он и так имеет доступ. Это защита
от случайной утечки: ключ нельзя прочитать из файлов проекта, нельзя
закоммитить, нельзя увидеть в логах агента.
"""
from __future__ import annotations

import base64
import hashlib
import json
from datetime import datetime, timezone

from . import config

_client = None
_unavailable = False

SECRETS_TABLE = "agent_secrets"

# Префиксы ключей, которые хранить можно. Всё остальное отклоняется,
# чтобы агент случайно не засунул в базу мусор.
# AGENT_ тоже разрешён: модели естественно называть «AGENT_API_KEY»,
# и без этого префикса агент путается и подставляет другие имена.
ALLOWED_PREFIXES = (
    "RENDER_", "GITHUB_", "VERCEL_", "AWS_", "SUPABASE_",
    "OPENROUTER_", "GROQ_", "GEMINI_", "AG_", "AGENT_",
    "ANTHROPIC_", "DB_", "API_",
)

# Явный запрет: эти имена нельзя перезаписывать, иначе агент
# может сломать собственное хранилище или авторизацию.
PROTECTED = ("ADMIN_TOKEN", "SUPABASE_KEY", "SUPABASE_URL")


def _get_client():
    """Клиент Supabase. Общий с memory.py, но держим свой."""
    global _client, _unavailable
    if _unavailable:
        return None
    if _client is not None:
        return _client
    if not config.memory_enabled():
        _unavailable = True
        return None
    try:
        from supabase import create_client

        _client = create_client(config.SUPABASE_URL, config.SUPABASE_KEY)
        return _client
    except Exception:
        _unavailable = True
        return None


# ---------------------------------------------------------------------------
# Шифрование
# ---------------------------------------------------------------------------

def _fernet():
    """Fernet с ключом, выведенным из ADMIN_TOKEN.

    Хеш SHA-256 даёт ровно 32 байта — это и есть требуемая длина
    ключа Fernet (base64url от 32 байт). Так мастер-ключ один,
    а шифротекст можно хранить в базе как есть.
    """
    from cryptography.fernet import Fernet

    token = config.ADMIN_TOKEN
    if not token or token == "dev-token":
        raise RuntimeError(
            "ADMIN_TOKEN не настроен: без него нельзя шифровать секреты")
    digest = hashlib.sha256(token.encode("utf-8")).digest()
    return Fernet(base64.urlsafe_b64encode(digest))


def encrypt(value: str) -> str:
    """Шифрует строку, возвращает base64-текст для хранения в базе."""
    return _fernet().encrypt(value.encode("utf-8")).decode("ascii")


def decrypt(ciphertext: str) -> str:
    """Расшифровывает значение из базы."""
    return _fernet().decrypt(ciphertext.encode("ascii")).decode("utf-8")


# ---------------------------------------------------------------------------
# Схема таблицы
# ---------------------------------------------------------------------------

DDL = """
create table if not exists agent_secrets (
    id bigint generated by default as identity primary key,
    name text not null unique,
    value text not null,
    note text,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);
create index if not exists agent_secrets_name_idx on agent_secrets(name);
"""


def ensure_table() -> dict:
    """Создаёт таблицу, если её нет.

    Python-клиент supabase не умеет DDL. Поэтому идём через
    Management API — но только если задан SUPABASE_ACCESS_TOKEN.
    Без токена проверяем простым SELECT: возможно, таблицу создали
    вручную через SQL Editor.
    """
    client = _get_client()
    if client is None:
        return {"ok": False, "reason": "нет подключения к Supabase"}

    # 1. Пробуем Management API — он умеет DDL
    token = config.SUPABASE_ACCESS_TOKEN
    ref = config.SUPABASE_PROJECT_REF
    if token and ref:
        try:
            import httpx

            r = httpx.post(
                f"https://api.supabase.com/v1/projects/{ref}/database/query",
                headers={"Authorization": f"Bearer {token}",
                         "Content-Type": "application/json"},
                json={"query": DDL},
                timeout=45.0,
            )
            if r.status_code < 300:
                return {"ok": True, "method": "management_api"}
            detail = r.text[:200]
        except Exception as exc:
            detail = f"{type(exc).__name__}: {exc}"

        # 2. Management API не сработал — возможно, таблица уже есть
        try:
            client.table(SECRETS_TABLE).select("name").limit(1).execute()
            return {"ok": True, "method": "already_exists",
                    "note": f"Management API: {detail}"}
        except Exception:
            return {"ok": False, "method": "management_api",
                    "reason": detail}
    else:
        # Токена нет — только проверяем доступ
        try:
            client.table(SECRETS_TABLE).select("name").limit(1).execute()
            return {"ok": True, "method": "already_exists"}
        except Exception as exc:
            return {"ok": False, "method": "select",
                    "reason": f"{type(exc).__name__}: {str(exc)[:200]}"}


# ---------------------------------------------------------------------------
# CRUD
# ---------------------------------------------------------------------------

def _valid_name(name: str) -> tuple[bool, str]:
    """Проверяет имя секрета: только безопасный формат."""
    if not name or not name.strip():
        return False, "Имя секрета пустое"
    name = name.strip()
    if name in PROTECTED:
        return False, f"«{name}» защищён от изменения через хранилище"
    if len(name) > 64:
        return False, "Имя длиннее 64 символов"
    if not name.replace("_", "").replace("-", "").isalnum():
        return False, "Имя может содержать только латиницу, цифры, _ и -"
    if not name.startswith(ALLOWED_PREFIXES):
        return False, ("Имя должно начинаться с одного из: "
                       + ", ".join(ALLOWED_PREFIXES)
                       + ". Например: RENDER_API_KEY, GITHUB_TOKEN, "
                         "AGENT_API_KEY")
    return True, ""


def set_secret(name: str, value: str, note: str = "", project: str = "") -> dict:
    """Сохраняет или обновляет секрет (зашифрованным) для конкретного проекта."""
    ok, why = _valid_name(name)
    if not ok:
        return {"ok": False, "error": why}
    if not value or not value.strip():
        return {"ok": False, "error": "Значение секрета пустое"}

    proj = (project or config.get_current_project() or "default").strip() or "default"
    client = _get_client()
    if client is None:
        return {"ok": False, "error": "нет подключения к Supabase"}

    try:
        payload = {
            "name": name.strip(),
            "value": encrypt(value.strip()),
            "note": (note or "").strip()[:200],
            "project": proj,
            "updated_at": datetime.now(timezone.utc).isoformat(),
        }
        # Сначала пробуем обновить по связке (project, name)
        upd = (client.table(SECRETS_TABLE)
               .update(payload)
               .eq("project", proj)
               .eq("name", name.strip())
               .execute())
        if getattr(upd, "data", None):
            return {"ok": True, "action": "updated", "name": name.strip(), "project": proj}

        client.table(SECRETS_TABLE).insert(payload).execute()
        return {"ok": True, "action": "created", "name": name.strip(), "project": proj}
    except Exception as exc:
        return {"ok": False, "error": f"{type(exc).__name__}: {str(exc)[:200]}"}


def get_secret(name: str, project: str = "") -> dict:
    """Достаёт и расшифровывает секрет. Сначала ищет в проекте, затем в default."""
    client = _get_client()
    if client is None:
        return {"ok": False, "error": "нет подключения к Supabase"}

    proj = (project or config.get_current_project() or "default").strip() or "default"
    try:
        # 1. Ищем секрет конкретного проекта
        r = (client.table(SECRETS_TABLE)
             .select("name, value, note, project, updated_at")
             .eq("project", proj)
             .eq("name", name.strip())
             .limit(1)
             .execute())
        rows = r.data or []

        # 2. Если в проекте нет, проверяем глобальный/default
        if not rows and proj != "default":
            r_def = (client.table(SECRETS_TABLE)
                     .select("name, value, note, project, updated_at")
                     .eq("project", "default")
                     .eq("name", name.strip())
                     .limit(1)
                     .execute())
            rows = r_def.data or []

        if not rows:
            return {"ok": False, "error": f"Секрет «{name}» не найден"}
        row = rows[0]
        return {
            "ok": True,
            "name": row["name"],
            "value": decrypt(row["value"]),
            "note": row.get("note", ""),
            "project": row.get("project", proj),
            "updated_at": str(row.get("updated_at", "")),
        }
    except Exception as exc:
        return {"ok": False, "error": f"{type(exc).__name__}: {str(exc)[:200]}"}


def list_secrets(project: str | None = None) -> list[dict]:
    """Список секретов БЕЗ значений — фильтруется по проекту."""
    client = _get_client()
    if client is None:
        return []
    try:
        q = client.table(SECRETS_TABLE).select("name, note, project, created_at, updated_at")
        if project:
            q = q.eq("project", project.strip())
        r = q.order("name", desc=False).execute()
        out = []
        for row in (r.data or []):
            out.append({
                "name": row["name"],
                "note": row.get("note", ""),
                "project": row.get("project", "default"),
                "updated_at": str(row.get("updated_at", "")),
            })
        return out
    except Exception:
        return []


def delete_secret(name: str, project: str = "") -> dict:
    """Удаляет секрет внутри конкретного проекта."""
    ok, why = _valid_name(name)
    if not ok:
        return {"ok": False, "error": why}
    client = _get_client()
    if client is None:
        return {"ok": False, "error": "нет подключения к Supabase"}
    proj = (project or config.get_current_project() or "default").strip() or "default"
    try:
        r = (client.table(SECRETS_TABLE)
             .delete()
             .eq("project", proj)
             .eq("name", name.strip())
             .execute())
        if getattr(r, "data", None):
            return {"ok": True, "deleted": name.strip(), "project": proj}
        return {"ok": False, "error": f"Секрет «{name}» не найден в проекте «{proj}»"}
    except Exception as exc:
        return {"ok": False, "error": f"{type(exc).__name__}: {str(exc)[:200]}"}


def names(project: str = "") -> list[str]:
    """Только имена — чтобы подставлять в HTTP-запросы."""
    return [s["name"] for s in list_secrets(project=project)]


def status() -> dict:
    """Состояние хранилища для /api/status."""
    client = _get_client()
    if client is None:
        return {"enabled": False, "count": 0}
    try:
        r = client.table(SECRETS_TABLE).select("name").execute()
        return {"enabled": True, "count": len(r.data or [])}
    except Exception:
        return {"enabled": False, "count": 0}